### PR TITLE
initial commit for feature1

### PR DESCRIPTION
**Pull request by DeepaS123**
added new file and edited file

### CODE REVIEW

**Review by kirancs1999 — CHANGES_REQUESTED** [review]
in first.txt and second.txt contents is not starting with upper case

**Comment by DeepaS123** [comment]
requested changes done

**Review by kirancs1999 — APPROVED** [review]
ok with the changes

**Review by kirancs1999 — APPROVED** [review]
happy with the changes

**Comment by DeepaS123** [comment]
approved so merging

**Pull request merged**
